version: 2.1

alpine_image: &pythonImage
  docker:
    - image: circleci/python:3.7
commands:
  activate_venv:
    description: Activates python virtual environment using source ~/.devops/bin/activate
    steps:
      - run:
          name: source venv
          command: |
            source ~/.devops/bin/activate

jobs:
  setup_virtual_environment:
    <<: *pythonImage
    steps:
      - checkout
      - restore_cache:
          keys:
              - v2-pip-deps-{{ checksum "requirements.txt" }}
              - v2-pip-deps-
      - run:
          name: create python virtual environment
          working_directory: .
          command: |
            pwd
            ls -la
            make setup
      - activate_venv
      - run:
          name: installing python dependencies
          command: make install

      - run:
          name: installing hadolint and minikube
          command: | 
            pwd
            ls -la
            sudo make install-all

      - save_cache:
            key: v2-pip-deps-{{ checksum "requirements.txt" }}
            paths:
                - ~/.devops

      - persist_to_workspace:
          root: /bin
          paths:
            - hadolint
            - minikube
  test:
    <<: *pythonImage
    steps:
      - checkout
      - restore_cache:
          keys:
              - v2-pip-deps-{{ checksum "requirements.txt" }}
              - v2-pip-deps-

      - activate_venv
      - run:
          name: run unit tests
          working_directory: .
          command: |
            ls -la
            pip freeze
            make test
  lint:
    <<: *pythonImage
    steps:
      - checkout
      - attach_workspace:
          at: /bin
      - restore_cache:
          keys:
              - v2-pip-deps-{{ checksum "requirements.txt" }}
              - v2-pip-deps-
      - activate_venv
      - run:
          name: lint project
          working_directory: .
          command: |
            make lint
  
  start:
    <<: *pythonImage
    steps:
      - checkout
      - attach_workspace:
          at: /bin
      - restore_cache:
          keys:
              - v2-pip-deps-{{ checksum "requirements.txt" }}
              - v2-pip-deps-
      - activate_venv
      - run:
          name: start app
          working_directory: .
          command: make run

workflows:
  udapepole:
    jobs:
      - setup_virtual_environment
      - test:
          requires: [setup_virtual_environment]
      - lint:
          requires: [test]
      - start:
          requires: [lint]