version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.12.0

alpine_image: &pythonImage
  docker:
    - image: circleci/python:3.7
      environment:
        TAR_OPTIONS: --no-same-owner

commands:
  activate_venv:
    description: Activates python virtual environment using source ~/.devops/bin/activate
    steps:
      - run:
          name: source venv
          command: |
            source ~/.devops/bin/activate

jobs:
  setup_virtual_environment:
    <<: *pythonImage
    steps:
      - checkout
      - restore_cache:
          keys:
              - v3-pip-deps-{{ checksum "requirements.txt" }}
              - v3-pip-deps-
      - run:
          name: create python virtual environment
          command: |
            pwd
            ls -la
            make setup
      # - activate_venv
      - run:
          name: installing python dependencies
          command: |
            source ~/.devops/bin/activate
            make install
            pip freeze

      - run:
          name: installing hadolint and minikube
          command: | 
            pwd
            ls -la
            sudo make install-all

      - save_cache:
            key: v3-pip-deps-{{ checksum "requirements.txt" }}
            paths:
                - ~/.devops

      - run:
          name: check bin folder
          command: |
            cd /bin
            ls -la

  test:
    <<: *pythonImage
    steps:
      - checkout
      - restore_cache:
          keys:
              - v3-pip-deps-{{ checksum "requirements.txt" }}
              - v3-pip-deps-
      - run:
          name: run unit tests
          command: |
            source ~/.devops/bin/activate
            make test

  lint:
    <<: *pythonImage
    steps:
      - checkout
      - restore_cache:
          keys:
              - v3-pip-deps-{{ checksum "requirements.txt" }}
              - v3-pip-deps-
      - run:
          name: lint project
          command: |
            source ~/.devops/bin/activate
            sudo make install-all
            make lint

workflows:
  udapepole:
    jobs:
      - setup_virtual_environment
      - test:
          requires: [setup_virtual_environment]
      - lint:
          requires: [test]